
      <aside>
        <form id="subscribe" name="subscribe">
          <div class="sidebox">
            <div class="form-group fm">
                <label>Full Name:</label>
                <input type="text" name="name" class="form-control in" >
                <span id="nameErr" class="error"></span>
            </div><br />
            <div class="form-group fm radio_pick">
                <label>Which animation company do you like most?</label><br />
                <input type="radio" name="favorite" value="disney"><label>Disney</label> <br>
                <input type="radio" name="favorite" value="dreamworks"><label>DreamWorks</label> <br>
                <input type="radio" name="favorite" value="pixar"><label>Pixar</label>
                <span id="selectErr" class="error"></span>
            </div>

            <div class="form-group fm bt">
                <input type="submit" class="btn bg-button-gold" value="Submit">
            </div>
          </div>
      </form>
      </aside>
