      <form method="post" action="survey_result.php">
        <div class="name">
          <label for="name">Name: </label>
          <input type="text" name="name" id="name">
        </div>
        <div class="radio_pick">
          <input type="radio" name="favorite" value="disney"> Disney<br>
          <input type="radio" name="favorite" value="dreamworks"> DreamWorks<br>
          <input type="radio" name="favorite" value="pixar"> Pixar
        </div>
        <input type="submit" value="Submit">
      </form>
